#!/bin/bash -e

cd "$(dirname "$0")"

pushd . > /dev/null

. "./raspberrypi-mediacenter-lib.sh"

if [ -f "./raspberrypi-mediacenter-config.sh" ]; then
	. "./raspberrypi-mediacenter-config.sh"
fi

if [ $UID != 0 ]; then
	echo "this script must be run as root"
	exit 1
fi

#############################################################################
# system packages
#############################################################################

if [ "${enable_apt_purge:-true}" == "true" ]; then
	echo "purging packages..."
	apt-get -y purge minecraft-pi sonic-pi wolfram-engine
fi

echo "updating packages..."

if [ "${enable_apt_update:-true}" == "true" ]; then
	apt-get -y update
fi

if [ "${enable_apt_upgrade:-true}" == "true" ]; then
	if [ "${enable_apt_dist_upgrade:-true}" == "true" ]; then
		apt-get -y dist-upgrade
	else
		apt-get -y upgrade
	fi
fi

if [ "$enable_rpi_update:-true}" == "true" ]; then
	rpi-update
fi

DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
	automake \
	binutils \
	build-essential \
	ca-certificates \
	cmake \
	dstat \
	g++-4.7 \
	g++-4.8 \
	gcc-4.7 \
	gcc-4.8 \
	git-core \
	htop \
	libapr1 \
	libaprutil1 \
	libasound2-dev \
	libboost-chrono1.50.0 \
	libboost-date-time1.50-dev \
	libboost-date-time1.50.0 \
	libboost-filesystem1.50-dev \
	libboost-filesystem1.50.0 \
	libboost-locale1.50-dev \
	libboost-locale1.50.0 \
	libboost-serialization1.50.0 \
	libboost-system1.50-dev \
	libboost-system1.50.0 \
	libboost-thread1.50.0 \
	libboost1.50-dev \
	libcurl4-openssl-dev \
	libdbus-1-dev \
	libeigen3-dev \
	libfreeimage-dev \
	libfreeimage3 \
	libfreetype6 \
	libfreetype6-dev \
	libgnutls-openssl27 \
	libgnutlsxx28 \
	libgssrpc4 \
	libidn11-dev \
	libkadm5clnt-mit9 \
	libkadm5srv-mit9 \
	libkdb5-7 \
	libneon27-gnutls \
	libpcre3-dev \
	libpcrecpp0 \
	libpython3.2 \
	libraw10 \
	libserf-1-1 \
	libsmbclient-dev \
	libssh-dev \
	libssl-dev \
	libtasn1-6-dev \
	libudev-dev \
	libusb-1.0-0-dev \
	libva1 \
	libxml2-dev \
	pkg-config \
	python3-dev \
	raspi-config \
	rpi-update \
	screen \
	sed \
	subversion \
	sysstat \
	vim \
	wget

#############################################################################
# update firmware
#############################################################################

if [ "${enable_rpi_update:-true}" == "true" ]; then
	echo "updating firmware..."
	rpi-update
fi

#############################################################################
# init file system
#############################################################################

lib_mkdir "/src"

cd /src

#############################################################################
# SDL2
#############################################################################

echo "building SDL2..."

if ! lib_test_sha256sum SDL2-2.0.3.tar.gz a5a69a6abf80bcce713fa873607735fe712f44276a7f048d60a61bb2f6b3c90c; then
	wget -O SDL2-2.0.3.tar.gz https://libsdl.org/release/SDL2-2.0.3.tar.gz
fi

if [ ! -d SDL2-2.0.3 ]; then
	tar -xzf SDL2-2.0.3.tar.gz
fi

if [ ! -f SDL2-2.0.3/Makefile ]; then
	cd SDL2-2.0.3
	./configure --disable-video-opengl --host=arm-raspberry-linux-gnueabihf
	cd ..
fi

if [ ! -f SDL2-2.0.3/build/.libs/libSDL2.so ]; then
	cd SDL2-2.0.3
	make
	cd ..
fi

if [ ! -f /usr/local/lib/libSDL2.so ]; then
	cd SDL2-2.0.3
	make install
	ldconfig
	cd ..
fi

#############################################################################
# SDL2 image
#############################################################################

echo "building SDL2 image..."

if ! lib_test_sha256sum SDL2_image-2.0.0.tar.gz b29815c73b17633baca9f07113e8ac476ae66412dec0d29a5045825c27a47234; then
	wget -O SDL2_image-2.0.0.tar.gz https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
fi

if [ ! -d SDL2_image-2.0.0 ]; then
	tar -xzf SDL2_image-2.0.0.tar.gz
fi

if [ ! -f SDL2_image-2.0.0/Makefile ]; then
	cd SDL2_image-2.0.0
	./configure
	cd ..
fi

if [ ! -f SDL2_image-2.0.0/.libs/libSDL2_image.so ]; then
	cd SDL2_image-2.0.0
	make
	cd ..
fi

if [ ! -f /usr/local/lib/libSDL2_image.so ]; then
	cd SDL2_image-2.0.0
	make install
	ldconfig
	cd ..
fi

#############################################################################
# SDL2 mixer
#############################################################################

echo "building SDL2 mixer..."

if ! lib_test_sha256sum SDL2_mixer-2.0.0.tar.gz a8ce0e161793791adeff258ca6214267fdd41b3c073d2581cd5265c8646f725b; then
	wget -O SDL2_mixer-2.0.0.tar.gz https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz
fi

if [ ! -d SDL2_mixer-2.0.0 ]; then
	tar -xzf SDL2_mixer-2.0.0.tar.gz
fi

if [ ! -f SDL2_mixer-2.0.0/Makefile ]; then
	cd SDL2_mixer-2.0.0
	./configure
	cd ..
fi

if [ ! -f SDL2_mixer-2.0.0/build/.libs/libSDL2_mixer.so ]; then
	cd SDL2_mixer-2.0.0
	make
	cd ..
fi

if [ ! -f /usr/local/lib/libSDL2_mixer.so ]; then
	cd SDL2_mixer-2.0.0
	make install
	ldconfig
	cd ..
fi

#############################################################################
# SDL2 ttf
#############################################################################

echo "building SDL2 ttf..."

if ! lib_test_sha256sum SDL2_ttf-2.0.12.tar.gz 8728605443ea1cca5cad501dc34dc0cb15135d1e575551da6d151d213d356f6e; then
	wget -O SDL2_ttf-2.0.12.tar.gz https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz
fi

if [ ! -d SDL2_ttf-2.0.12 ]; then
	tar -xzf SDL2_ttf-2.0.12.tar.gz
fi

if [ ! -f SDL2_ttf-2.0.12/Makefile ]; then
	cd SDL2_ttf-2.0.12
	./configure
	cd ..
fi

if [ ! -f SDL2_ttf-2.0.12/.libs/libSDL2_ttf.so ]; then
	cd SDL2_ttf-2.0.12
	make
	cd ..
fi

if [ ! -f /usr/local/lib/libSDL2_ttf.so ]; then
	cd SDL2_ttf-2.0.12
	make install
	ldconfig
	cd ..
fi

#############################################################################
# RetroArch
#############################################################################

echo "building RetroArch..."

if ! lib_test_sha256sum RetroArch-1.2.tar.gz 07cb30ae1698239b52e3b54b02e9cc7475660d14bb1da27ef809786f6b8be674; then
	wget -O RetroArch-1.2.tar.gz https://github.com/libretro/RetroArch/archive/v1.2.tar.gz
fi

if [ ! -d RetroArch-1.2 ]; then
	tar -xzf RetroArch-1.2.tar.gz
fi

if [ ! -f RetroArch-1.2/config.h ]; then
	cd RetroArch-1.2
	./configure
	cd ..
fi

if [ ! -f RetroArch-1.2/retroarch ]; then
	cd RetroArch-1.2
	make
	cd ..
fi

if [ ! -f /usr/local/bin/retroarch ]; then
	mkdir -p /usr/local/share/retroarch/emulators
	cd RetroArch-1.2
	make install
	ldconfig
	cd ..
fi

#############################################################################
# Nintendo Entertainment System
#############################################################################

if [ "${enable_emulator_nes:-true}" == "true" ]; then

echo "building NES emulator..."

if [ ! -f libretro-nes/Makefile.libretro ]; then
	git clone --depth 1 https://github.com/libretro/libretro-fceumm libretro-nes
fi

if [ ! -f libretro-nes/fceumm_libretro.so ]; then
	cd libretro-nes
	make -f Makefile.libretro
	cd ..
fi

if [ ! -f /usr/local/share/retroarch/emulators/fceumm_libretro.so ]; then
	cp libretro-nes/fceumm_libretro.so /usr/local/share/retroarch/emulators/fceumm_libretro.so
fi

fi

#############################################################################
# Sega Genesis
#############################################################################

if [ "${enable_emulator_megadrive:-true}" == "true" ]; then

echo "building Sega Genesis emulator..."

if [ ! -f libretro-megadrive/Makefile.libretro ]; then
	git clone --depth 1 https://github.com/libretro/Genesis-Plus-GX libretro-megadrive
fi

if [ ! -f libretro-megadrive/genesis_plus_gx_libretro.so ]; then
	cd libretro-megadrive
	make -f Makefile.libretro
	cd ..
fi

if [ ! -f /usr/local/share/retroarch/emulators/genesis_plus_gx_libretro.so ]; then
	cp libretro-megadrive/genesis_plus_gx_libretro.so /usr/local/share/retroarch/emulators/genesis_plus_gx_libretro.so
fi

fi

#############################################################################
# Super Nintendo
#############################################################################

if [ "${enable_emulator_snes:-true}" == "true" ]; then

echo "building Super Nintendo emulator..."

if [ ! -f libretro-snes/Makefile.libretro ]; then
	git clone --depth 1 https://github.com/libretro/snes9x-next libretro-snes
fi

if [ ! -f libretro-snes/snes9x_next_libretro.so ]; then
	cd libretro-snes
	make -f Makefile.libretro
	cd ..
fi

if [ ! -f /usr/local/share/retroarch/emulators/snes9x_next_libretro.so ]; then
	cp libretro-snes/snes9x_next_libretro.so /usr/local/share/retroarch/emulators/snes9x_next_libretro.so
fi

fi

#############################################################################
# PlayStation 1
#############################################################################

if [ "${enable_emulator_pcsx:-true}" == "true" ]; then

if [ ! -f libretro-pcsx_rearmed/Makefile.libretro ]; then
	git clone --depth 1 https://github.com/notaz/pcsx_rearmed libretro-pcsx_rearmed
fi

if [ ! -f libretro-pcsx_rearmed/pcsx_rearmed_libretro.so ]; then
	cd libretro-pcsx_rearmed
	make -f Makefile.libretro
	cd ..
fi

if [ ! -f /usr/local/share/retroarch/emulators/pcsx_rearmed_libretro.so ]; then
	cp libretro-pcsx_rearmed/pcsx_rearmed_libretro.so /usr/local/share/retroarch/emulators/pcsx_rearmed_libretro.so
fi

fi

#############################################################################
# M.A.M.E.
#############################################################################

if [ "${enable_emulator_mame:-false}" == "true" ]; then

if [ ! -f libretro-imame4all/makefile.libretro ] ;then
	git clone --depth 1 https://github.com/libretro/imame4all-libretro libretro-imame4all
fi

if [ ! -f libretro-imame4all/libretro.so ]; then
	cd libretro-imame4all
	make -f makefile.libretro ARM=1
	cd ..
fi

if [ ! -f /usr/local/share/retroarch/emulators/imame4all_libretro.so ]; then
	cp libretro-imame4all/libretro.so /usr/local/share/retroarch/emulators/imame4all_libretro.so
fi

fi

#############################################################################
# ffmpeg
#############################################################################

if [ "${enable_ffmpeg:-true}" == "true" ]; then

echo "building ffmpeg..."

if [ ! -f ffmpeg/configure ]; then
	git clone https://github.com/FFmpeg/FFmpeg ffmpeg
	cd ffmpeg
	git checkout n2.7.1
	cd ..
fi

if [ ! -f ffmpeg/config.h ]; then
	cd ffmpeg
	./configure \
			--arch=arm \
			--cpu=arm1176jzf-s \
			--disable-armv5te \
			--disable-crystalhd \
			--disable-debug \
			--disable-doc \
			--disable-hwaccels \
			--disable-libsmbclient \
			--disable-libssh \
			--disable-neon \
			--disable-network \
			--disable-openssl \
			--disable-runtime-cpudetect \
			--enable-armv6 \
			--enable-armv6t2 \
			--enable-ffmpeg \
			--enable-gpl \
			--enable-hardcoded-tables \
			--enable-nonfree \
			--enable-pic \
			--enable-pthreads \
			--enable-shared \
			--enable-version3 \
			--extra-cflags="-mfpu=vfp -mfloat-abi=hard -mno-apcs-stack-check -mstructure-size-boundary=32 -mno-sched-prolog" \
			--target-os=linux
	cd ..
fi

if [ ! -f ffmpeg/libavformat/libavformat.so ]; then
	cd ffmpeg
	make -j4
	cd ..
fi

if [ ! -f /usr/local/lib/libavformat.so ]; then
	cd ffmpeg
	make install
	ldconfig
	cd ..
fi

fi

#############################################################################
# omxplayer
#############################################################################

if [ "${enable_omxplayer:-true}" == "true" ]; then

echo "building omxplayer..."

if [ ! -f omxplayer/prepare-native-raspbian.sh ]; then
	git clone --depth 1 https://github.com/popcornmix/omxplayer.git omxplayer
fi

if [ ! -f omxplayer/omxplayer.bin ]; then
	cd omxplayer
	sed -i 's/^[^#].*cp -a ffmpeg_compiled.*/#\0/' Makefile
	./prepare-native-raspbian.sh
	make
	cd ..
fi

if [ ! -f /usr/local/bin/omxplayer.bin ]; then
	cp omxplayer/omxplayer /usr/local/bin/omxplayer
	cp omxplayer/omxplayer.bin /usr/local/bin/omxplayer.bin
fi

chmod 755 /usr/local/bin/omxplayer /usr/local/bin/omxplayer.bin

fi

#############################################################################
# Emulation Station
#############################################################################

if [ "${enable_emulation_station:-true}" == "true" ]; then

echo "building Emulation Station..."

if [ ! -f emulationstation/README.md ]; then
	git clone --depth 1 https://github.com/Aloshi/EmulationStation emulationstation
fi

if [ ! -f emulationstation/Makefile ]; then
	cd emulationstation
	cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8 -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/ .
	cd ..
fi

if [ ! -f emulationstation/emulationstation ]; then
	cd emulationstation
	make
	cd ..
fi

if [ ! -f /usr/local/bin/emulationstation ]; then
	cd emulationstation
	make install
	ldconfig
	cd ..
fi

fi

#############################################################################
# configuration
#############################################################################

popd > /dev/null

if [ "${enable_config:-true}" == "true" ]; then

echo "configuring UI..."

mkdir -p /home/pi/.emulationstation
cp -R config/* /home/pi/.emulationstation
chown -R pi.pi /home/pi/.emulationstation

fi

#############################################################################
# cleanup
#############################################################################

if [ "${enable_apt_remove:-true}" == "true" ]; then

echo "removing packages..."

apt-get -y remove \
	automake \
    binutils \
    build-essential \
    cmake \
    g++-4.8 \
    gcc-4.8 \
    libasound2-dev \
    libboost-date-time-dev \
    libboost-filesystem-dev \
    libboost-locale-dev \
    libboost-system-dev \
    libboost1.50-dev \
    libcurl4-openssl-dev \
    libdbus-1-dev \
    libeigen3-dev \
    libfreeimage-dev \
    libfreetype6-dev \
    libidn11-dev \
    libpcre3-dev \
    libsmbclient-dev \
    libssh-dev \
    libssl-dev \
    libudev-dev \
    libusb-1.0-0-dev \
    libxml2-dev \
    python3-dev \
    subversion

if [ "${enable_apt_autoremove:-true}" == "true" ]; then
	apt-get -y autoremove
fi

fi
