---
- name: ffmpeg clone
  git: repo=https://github.com/FFmpeg/FFmpeg
       dest=/src/ffmpeg
       version=n2.7.1
       depth=1

- name: ffmpeg configure
  shell: ./configure \
    --arch=arm \
    --cpu=arm1176jzf-s \
    --disable-armv5te \
    --disable-crystalhd \
    --disable-debug \
    --disable-doc \
    --disable-hwaccels \
    --disable-libsmbclient \
    --disable-libssh \
    --disable-neon \
    --disable-network \
    --disable-openssl \
    --disable-runtime-cpudetect \
    --enable-armv6 \
    --enable-armv6t2 \
    --enable-ffmpeg \
    --enable-gpl \
    --enable-hardcoded-tables \
    --enable-nonfree \
    --enable-pic \
    --enable-pthreads \
    --enable-shared \
    --enable-version3 \
    --extra-cflags="-mfpu=vfp -mfloat-abi=hard -mno-apcs-stack-check -mstructure-size-boundary=32 -mno-sched-prolog" \
    --target-os=linux
  args:
    chdir: /src/ffmpeg
    creates: /src/ffmpeg/config.h

- name: ffmpeg make
  shell: make -j4
  args:
    chdir: /src/ffmpeg
    creates: /src/ffmpeg/libavformat/libavformat.so

- name: ffmpeg install
  shell: make install
  register: installed
  args:
    chdir: /src/ffmpeg
    creates: /usr/local/lib/libavformat.so

- name: ffmpeg ldconfig
  shell: ldconfig
  when: installed|changed
