---
- name: libretro clone
  git: repo=https://github.com/libretro/libretro-super
       dest=/src/libretro-super
       depth=1

- name: libretro retroarch fetch
  shell: ./libretro-fetch.sh --retroarch
  args:
    chdir: /src/libretro-super
    creates: /src/libretro-super/retroarch

- name: libretro retroarch configure
  shell: ./configure --prefix=/usr/local
  args:
    chdir: /src/libretro-super/retroarch
    creates: /src/libretro-super/retroarch/config.h

- name: libretro retroarch build
  shell: make
  args:
    chdir: /src/libretro-super/retroarch
    creates: /src/libretro-super/retroarch/retroarch

- name: libretro retroarch install
  shell: make install
  args:
    chdir: /src/libretro-super/retroarch
    creates: /usr/local/bin/retroarch

- file: state=directory path=/usr/local/share
- file: state=directory path=/usr/local/share/retroarch
- file: state=directory path=/usr/local/share/retroarch/emulators
