---
- name: sdl2 get
  get_url: dest=/src/SDL2-2.0.3.tar.gz sha256sum=a5a69a6abf80bcce713fa873607735fe712f44276a7f048d60a61bb2f6b3c90c url=https://libsdl.org/release/SDL2-2.0.3.tar.gz

- name: sdl2 unarchive
  unarchive: copy=no dest=/src src=/src/SDL2-2.0.3.tar.gz creates=/src/SDL2-2.0.3

- name: sdl2 configure
  shell: ./configure --disable-video-opengl --host=arm-raspberry-linux-gnueabihf
  args:
    chdir: /src/SDL2-2.0.3
    creates: /src/SDL2-2.0.3/Makefile

- name: sdl2 build
  shell: make
  args:
    chdir: /src/SDL2-2.0.3
    creates: /src/SDL2-2.0.3/build/.libs/libSDL2.so

- name: sdl2 install
  shell: make install
  register: installed
  args:
    chdir: /src/SDL2-2.0.3
    creates: /usr/local/lib/libSDL2.so

- name: sdl2 ldconfig
  shell: ldconfig
  when: installed|changed

- name: sdl2 image get
  get_url: dest=/src/SDL2_image-2.0.0.tar.gz sha256sum=b29815c73b17633baca9f07113e8ac476ae66412dec0d29a5045825c27a47234 url=https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz

- name: sdl2 image unarchive
  unarchive: copy=no dest=/src src=/src/SDL2_image-2.0.0.tar.gz creates=/src/SDL2_image-2.0.0

- name: sdl2 image configure
  shell: ./configure
  args:
    chdir: /src/SDL2_image-2.0.0
    creates: /src/SDL2_image-2.0.0/Makefile

- name: sdl2 image build
  shell: make
  args:
    chdir: /src/SDL2_image-2.0.0
    creates: /src/SDL2_image-2.0.0/.libs/libSDL2_image.so

- name: sdl2 image install
  shell: make install
  register: installed
  args:
    chdir: /src/SDL2_image-2.0.0
    creates: /usr/local/lib/libSDL2_image.so

- name: sdl2 image ldconfig
  shell: ldconfig
  when: installed|changed

- name: sdl2 mixer get
  get_url: dest=/src/SDL2_mixer-2.0.0.tar.gz sha256sum=a8ce0e161793791adeff258ca6214267fdd41b3c073d2581cd5265c8646f725b url=https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz

- name: sdl2 mixer unarchive
  unarchive: copy=no dest=/src src=/src/SDL2_mixer-2.0.0.tar.gz creates=/src/SDL2_mixer-2.0.0

- name: sdl2 mixer configure
  shell: ./configure
  args:
    chdir: /src/SDL2_mixer-2.0.0
    creates: /src/SDL2_mixer-2.0.0/Makefile

- name: sdl2 mixer build
  shell: make
  args:
    chdir: /src/SDL2_mixer-2.0.0
    creates: /src/SDL2_mixer-2.0.0/build/.libs/libSDL2_mixer.so

- name: sdl2 mixer install
  shell: make install
  register: installed
  args:
    chdir: /src/SDL2_mixer-2.0.0
    creates: /usr/local/lib/libSDL2_mixer.so

- name: sdl2 mixer ldconfig
  shell: ldconfig
  when: installed|changed

- name: sdl2 ttf get
  get_url: dest=/src/SDL2_ttf-2.0.12.tar.gz sha256sum=8728605443ea1cca5cad501dc34dc0cb15135d1e575551da6d151d213d356f6e url=https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz

- name: sdl2 ttf unarchive
  unarchive: copy=no dest=/src src=/src/SDL2_ttf-2.0.12.tar.gz creates=/src/SDL2_ttf-2.0.12

- name: sdl2 ttf configure
  shell: ./configure
  args:
    chdir: /src/SDL2_ttf-2.0.12
    creates: /src/SDL2_ttf-2.0.12/Makefile

- name: sdl2 ttf build
  shell: make
  args:
    chdir: /src/SDL2_ttf-2.0.12
    creates: /src/SDL2_ttf-2.0.12/.libs/libSDL2_ttf.so

- name: sdl2 ttf install
  shell: make install
  register: installed
  args:
    chdir: /src/SDL2_ttf-2.0.12
    creates: /usr/local/lib/libSDL2_ttf.so

- name: sdl2 ttf ldconfig
  shell: ldconfig
  when: installed|changed
